CREATE DATABASE IF NOT EXISTS nba_veritabani
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE nba_veritabani;

CREATE TABLE Conference (
    ConferenceID INT AUTO_INCREMENT PRIMARY KEY,
    ConferenceName VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Team (
    TeamID INT PRIMARY KEY, 
    TeamName VARCHAR(255),
    TeamAbbreviation VARCHAR(10),
    LogoURL TEXT,
    ConferenceID INT,
    FOREIGN KEY (ConferenceID) REFERENCES Conference(ConferenceID)
);

CREATE TABLE Player (
    PlayerID INT PRIMARY KEY, 
    PlayerName VARCHAR(255),
    Position VARCHAR(50),
    HeadshotURL TEXT,
    TeamID INT,
    FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
);

CREATE TABLE TeamStats (
    TeamStatsID INT AUTO_INCREMENT PRIMARY KEY,
    TeamID INT,
    GP INT,
    W INT,
    L INT,
    W_PCT DECIMAL(5, 3),
    MIN DECIMAL(10, 2),
    DEF_RATING DECIMAL(10, 2),
    DREB DECIMAL(10, 2),
    DREB_PCT DECIMAL(5, 3),
    STL DECIMAL(10, 2),
    BLK DECIMAL(10, 2),
    GP_RANK INT,
    W_RANK INT,
    L_RANK INT,
    W_PCT_RANK INT,
    MIN_RANK INT,
    DEF_RATING_RANK INT,
    DREB_RANK INT,
    DREB_PCT_RANK INT,
    STL_RANK INT,
    BLK_RANK INT,
    FOREIGN KEY (TeamID) REFERENCES Team(TeamID),
    UNIQUE(TeamID)
);

CREATE TABLE OpponentStats (
    OpponentStatsID INT AUTO_INCREMENT PRIMARY KEY,
    TeamID INT,
    OPP_PTS_OFF_TOV DECIMAL(10, 2),
    OPP_PTS_2ND_CHANCE DECIMAL(10, 2),
    OPP_PTS_FB DECIMAL(10, 2),
    OPP_PTS_PAINT DECIMAL(10, 2),
    OPP_PTS_OFF_TOV_RANK INT,
    OPP_PTS_2ND_CHANCE_RANK INT,
    OPP_PTS_FB_RANK INT,
    OPP_PTS_PAINT_RANK INT,
    FOREIGN KEY (TeamID) REFERENCES Team(TeamID),
    UNIQUE(TeamID)
);

CREATE TABLE `Player Regular Season Performance` (
    PlayerStatsID INT AUTO_INCREMENT PRIMARY KEY,
    PlayerID INT,
    GP INT,
    W INT,
    L INT,
    MIN DECIMAL(10, 2),
    FGM DECIMAL(10, 2),
    FGA DECIMAL(10, 2),
    FG_PCT DECIMAL(5, 3),
    FG3M DECIMAL(10, 2),
    FG3A DECIMAL(10, 2),
    FG3_PCT DECIMAL(5, 3),
    FTM DECIMAL(10, 2),
    FTA DECIMAL(10, 2),
    FT_PCT DECIMAL(5, 3),
    OREB DECIMAL(10, 2),
    DREB DECIMAL(10, 2),
    REB DECIMAL(10, 2),
    AST DECIMAL(10, 2),
    TOV DECIMAL(10, 2),
    STL DECIMAL(10, 2),
    BLK DECIMAL(10, 2),
    BLKA DECIMAL(10, 2),
    PF DECIMAL(10, 2),
    PFD DECIMAL(10, 2),
    PTS DECIMAL(10, 2),
    PLUS_MINUS DECIMAL(10, 2),
    Efficiency DECIMAL(10, 2),
    FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID)
);

CREATE TABLE `Player Playoff Performance` (
    PlayerStatsID INT AUTO_INCREMENT PRIMARY KEY,
    PlayerID INT,
    GP INT,
    W INT,
    L INT,
    MIN DECIMAL(10, 2),
    FGM DECIMAL(10, 2),
    FGA DECIMAL(10, 2),
    FG_PCT DECIMAL(5, 3),
    FG3M DECIMAL(10, 2),
    FG3A DECIMAL(10, 2),
    FG3_PCT DECIMAL(5, 3),
    FTM DECIMAL(10, 2),
    FTA DECIMAL(10, 2),
    FT_PCT DECIMAL(5, 3),
    OREB DECIMAL(10, 2),
    DREB DECIMAL(10, 2),
    REB DECIMAL(10, 2),
    AST DECIMAL(10, 2),
    TOV DECIMAL(10, 2),
    STL DECIMAL(10, 2),
    BLK DECIMAL(10, 2),
    BLKA DECIMAL(10, 2),
    PF DECIMAL(10, 2),
    PFD DECIMAL(10, 2),
    PTS DECIMAL(10, 2),
    PLUS_MINUS DECIMAL(10, 2),
    Efficiency DECIMAL(10, 2),
    FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID)
);

CREATE TABLE Staging_Data (
    PLAYER_NAME TEXT, PLAYER_ID INT, TEAM_NAME_x TEXT, LOCATION TEXT,
    MIN_x DECIMAL(10, 2), FGM DECIMAL(10, 2), FGA DECIMAL(10, 2), FG_PCT DECIMAL(5, 3),
    FG3M DECIMAL(10, 2), FG3A DECIMAL(10, 2), FG3_PCT DECIMAL(5, 3), FTM DECIMAL(10, 2),
    FTA DECIMAL(10, 2), FT_PCT DECIMAL(5, 3), OREB DECIMAL(10, 2), DREB_x DECIMAL(10, 2),
    REB DECIMAL(10, 2), AST DECIMAL(10, 2), TOV DECIMAL(10, 2), STL_x DECIMAL(10, 2),
    BLK_x DECIMAL(10, 2), BLKA DECIMAL(10, 2), PF DECIMAL(10, 2), PFD DECIMAL(10, 2),
    PTS DECIMAL(10, 2), PLUS_MINUS DECIMAL(10, 2), Efficiency DECIMAL(10, 2),
    `Season Type` TEXT,
    GP_x INT, W_x INT, L_x INT, Logo_URL TEXT, DISPLAY_FIRST_LAST_x TEXT,
    TEAM_ID INT, TEAM_ABBREVIATION TEXT, HEADSHOT_URL TEXT, DISPLAY_FIRST_LAST_y TEXT,
    POSITION TEXT, TEAM_NAME_y TEXT, GP_y INT, W_y INT, L_y INT,
    W_PCT DECIMAL(5, 3), MIN_y DECIMAL(10, 2), DEF_RATING DECIMAL(10, 2),
    DREB_y DECIMAL(10, 2), DREB_PCT DECIMAL(5, 3), STL_y DECIMAL(10, 2),
    BLK_y DECIMAL(10, 2), OPP_PTS_OFF_TOV DECIMAL(10, 2), OPP_PTS_2ND_CHANCE DECIMAL(10, 2),
    OPP_PTS_FB DECIMAL(10, 2), OPP_PTS_PAINT DECIMAL(10, 2), GP_RANK INT, W_RANK INT,
    L_RANK INT, W_PCT_RANK INT, MIN_RANK INT, DEF_RATING_RANK INT, DREB_RANK INT,
    DREB_PCT_RANK INT, STL_RANK INT, BLK_RANK INT, OPP_PTS_OFF_TOV_RANK INT,
    OPP_PTS_2ND_CHANCE_RANK INT, OPP_PTS_FB_RANK INT, OPP_PTS_PAINT_RANK INT,
    Conference TEXT
);
